name: Flutter Nightly Build

on:
  schedule:
    # schedule build every day 1st & 15th of the month
    #- cron: "0 0 1,15 * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "nightly" 
permissions:
  contents: write
